name: Run Postman API Tests

on:
  push:
    branches:
      - main

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Chạy Postman collection test
        env:
          POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
        run: |
          postman collection run 42412959-c417bcf7-0673-48e2-804b-97ed37e2579b -e 42412959-0d30a94d-a5e0-4a4b-82f0-d4d36d0d56e2

      - name: Upload báo cáo test
        uses: actions/upload-artifact@v4
        with:
          name: postman-reports
          path: report/
